version: "3.8"

volumes: 
  productdata

networks: 
  frontend:
  backend:

services: 
  mysql:
    image: "mysql:8.0.0"
    volumes: 
      - productdata:/var/lib/mysql
    networks: 
      - backend
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - bind-address=0.0.0.0

dbinit:
  image: "registry.cn-hangzhou.aliyuncs.com/yoyosoft/exampleapp:mysql"
  networks: 
    - backend
  environment: 
    - INITDB=true
    - DBHOST=mysql
  depends_on: 
    - mysql
  
mvc:
  image: "registry.cn-hangzhou.aliyuncs.com/yoyosoft/exampleapp:mysql"
  networks: 
    - backend
    - frontend
  environment: 
    - DBHOST=mysql
  depends_on: 
    - mysql 
loadbalancer:
  image: "dockercloud/haproxy:1.2.1"
  ports: 
    - 3000:80
  links: 
    - mvc
  volumes: 
    - /var/run/docker.sock:/var/run/dock.sock
  networks: 
    - frontend
    